NEWS_API_KEY = "d3e138fbb96d490ab6e203a441c32311"

# Neo4j Aura Configuration
NEO4J_URI = "neo4j+s://a4ce5673.databases.neo4j.io"
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = "1XH4Ue5aH-D7LZLtMngdTA1nPvD5IBNrFdTcdAbpfJo"